[package]
name = "shard-den-json-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for JSON Extractor tool"

[[bin]]
name = "shard-den-json"
path = "main.rs"

[dependencies]
shard-den-json = { path = ".." }
shard-den-core = { workspace = true }
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
